language: php

php:
  - 7.1
  - 7.0
  - 5.6
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

sudo: false

before_script:
  - composer install

script:
  - ./vendor/bin/phpcs -d date.timezone=UTC

